export const FETCH_ORDEROFFLINE_REQUEST = 'FETCH_ORDEROFFLINE_REQUEST';
export const FETCH_USERDATA_REQUEST = 'FETCH_USERDATA_REQUEST';
export const FETCH_ROUTELIST_REQUEST = 'FETCH_ROUTELIST_REQUEST';
export const THEME_COLOR_TYPE = 'THEME_COLOR_TYPE';
export const FETCH_PRODUCT_CATEGORY_LIST = 'THEME_PRODUCT_CATEGORY_LIST';
export const FETCH_DO_LIST = 'FETCH_DO_LIST';
export const FETCH_DO_HOLD_LIST = 'FETCH_DO_HOLD_LIST';
export const FETCH_DO_CHECKED_LIST = 'FETCH_DO_CHECKED_LIST';